Embedded app
reshufflehq/random-cat pull request #1
Opened 2019-10-21 22:37 UTC by zolga

Simple app to demonstrate an embedded frame that displays cat's images.

the root page of the app is the Admin page, in this page, you can add links and create a list of URLs.
navigate to /live to watch random image from the list.

After 'reshuffle deploy', the app URL with path /live can be embedded in other web sites.

2019-10-23 02:05 UTC, rylandg requested changes
I will review the rest tomorrow, as you know I got pulled into a long discussion. My high level feedback is that the backend should use an object and not an array for the urls. And urls should not need ids.

Also I don't know why you changed the linting, but it seems like it's far less strict. What happened there?

Overall it's a nice idea and I look forward to reviewing the rest of the code.

2019-10-23 02:05 UTC, rylandg commented on .eslintrc.json
> +{
Weird, shouldn't this be part of the reshuffle template already?

2019-10-23 02:05 UTC, rylandg commented on backend/backend.js
> +export async function addNewUrl(link = {}) {
Why is the url itself not the key? If you wanted to allow multiple identical links, it seems to make more sense that the object be:

```js
{
  link: string;
  likelihood: number;
}
```

2019-10-23 02:05 UTC, rylandg commented on backend/backend.js
> +  return update('links', (list = []) => list.concat(link));
If you're using the same key multiple times, I recommend declaring it as a constant towards the top of the file.

2019-10-23 02:05 UTC, rylandg commented on backend/backend.js
> +export async function addNewUrl(link = {}) {
Also, why is an array used to store the links instead of a dictionary?

2019-10-23 02:05 UTC, rylandg commented on backend/backend.js
> +  return update('links', (list = []) => list.filter(link => link.id !== id));
This design means that multiple identical id's are ok, and that they will all be deleted.

2019-10-23 02:05 UTC, rylandg commented on package.json
> +    "eslint-plugin-react": "^7.16.0"
Can you explain why this has all been removed? Aren't these defined by CRA?

2019-10-23 02:05 UTC, rylandg commented on src/components/Admin/Admin.js
> +import './admin.css';
Your css files have inconsistent casing. Some start with upper `App.css` and others lower.

2019-10-23 02:05 UTC, rylandg commented on src/components/Admin/Admin.js
> +      fetchFromDb();
This `try/catch` doesn't actually do anything because you didn't await the `fetchFromDb` call.

2019-10-23 02:05 UTC, rylandg commented on src/components/Admin/Admin.js
> +      console.error('An error on fetch');
If you're going to bother catching the error I would make it more informative.

2019-10-23 02:05 UTC, rylandg commented on src/components/Admin/Admin.js
> +      let links = await getLinks();
Why is this let?

2019-10-23 02:05 UTC, rylandg commented on src/components/Admin/Admin.js
> +      let text = inputValue;
This is actually dangerous, why don't you pass in inputValue with the event?

2019-10-23 02:05 UTC, rylandg commented on src/components/Admin/Admin.js
> +      let text = inputValue;
Also don't understand the `let`

2019-10-23 02:05 UTC, rylandg commented on src/components/Admin/Admin.js
> +        id: generateRandomId(),
Please define functions before using them, I was very confused about where this was located.

2019-10-23 02:05 UTC, rylandg commented on src/components/Admin/Admin.js
> +      setLinksList(list.reverse());
Why is this reversed?

2019-10-23 02:05 UTC, rylandg commented on src/components/Admin/Admin.js
> +    } catch (error) {}
It's pretty dangerous to just swallow the error.

2019-10-23 02:05 UTC, rylandg commented on src/components/Admin/Admin.js
> +    return new Date().getTime();
I don't think you need to write this yourself, please don't do it this way.

2019-10-23 02:05 UTC, rylandg commented on src/components/Admin/Admin.js
> +    if (event.key === 'Enter') {
Please use the actual `Enter` identifier (part of the same API as `event`)

2019-10-23 02:05 UTC, rylandg commented on src/components/Admin/Admin.js
> +  const handleChange = event => {
Why is this separate from `handleAddLink`

2019-10-23 02:05 UTC, rylandg commented on src/components/Admin/Admin.js
> +  const handleChange = event => {
Destructure `{ key, target }` in the function props.

2019-10-23 19:58 UTC, rylandg requested changes
Those are the rest of my current comments.

2019-10-23 19:58 UTC, rylandg commented on src/components/Admin/Admin.js
> +      setLinksList(list.reverse());
I don't understand the reverse.

2019-10-23 19:58 UTC, rylandg commented on src/components/Admin/admin.css
> +.trimText {
Why is this class camelCase?

2019-10-23 19:58 UTC, rylandg commented on src/components/LiveFrame.js
> +const generateRandomNumber = list => {
This could be named much more clearly. Maybe something that indicates it's relationship with `list`.

2019-10-23 19:58 UTC, rylandg commented on src/components/LiveFrame.js
> +      fetchFromDb();
Same as above, no `await` means this code is broken.

2019-10-23 19:58 UTC, rylandg commented on src/components/LiveFrame.js
> +      let links = await getLinks();
why `let`?

2019-10-23 19:58 UTC, rylandg commented on src/components/LiveFrame.js
> +      setLinksList([...links]);
Why are you destructuring here? This has no effect.

2019-10-23 19:58 UTC, rylandg commented on src/components/LiveFrame.js
> +      console.error('error HandleClick');
nit: casing wrong for `HandleClick`

2019-10-23 19:58 UTC, rylandg commented on src/components/LiveFrame.js
> +      const random = generateRandomNumber(linksList);
Why is this in a `try`?

2019-10-24 18:02 UTC, zolga reviewed
@rylandg Thanks for your feedback and comments! 
I changed a lot of things, please take another look.

Thanks again!

2019-10-24 18:02 UTC, zolga commented on .eslintrc.json
> +{
I generated from blank, this file is not there.

2019-10-24 18:02 UTC, zolga commented on backend/backend.js
> +  return update('links', (list = []) => list.concat(link));
when you say 'same key' do you mean 'links' ?

2019-10-24 18:02 UTC, zolga commented on package.json
> +    "eslint-plugin-react": "^7.16.0"
This setting was not working well in my env, I followed eslint and prettier guidelines to reinstall and config.

2019-10-24 18:02 UTC, zolga commented on src/components/Admin/Admin.js
> +import './admin.css';
Changed, thanks!

2019-10-24 18:02 UTC, zolga commented on src/components/Admin/Admin.js
> +      let links = await getLinks();
You right, changed to const, thanks

2019-10-24 18:02 UTC, zolga commented on src/components/Admin/Admin.js
> +      fetchFromDb();
added await. thanks

2019-10-24 18:02 UTC, zolga commented on src/components/Admin/Admin.js
> +      let text = inputValue;
why this is dangerous? please explain your suggestion

2019-10-24 18:02 UTC, zolga commented on src/components/Admin/Admin.js
> +      let text = inputValue;
Changed to const.

2019-10-24 18:02 UTC, zolga commented on src/components/Admin/Admin.js
> +        id: generateRandomId(),
Moved.

2019-10-24 18:02 UTC, zolga commented on src/components/Admin/Admin.js
> +    return new Date().getTime();
Why? its a simple case of unique id.

2019-10-24 18:02 UTC, zolga commented on src/components/Admin/Admin.js
> +    } catch (error) {}
Do you mean because the block is empty? 

I added code to that block, let me know if this what you mean

2019-10-24 18:02 UTC, zolga commented on src/components/Admin/Admin.js
> +  const handleChange = event => {
this is separate because I don't want to add the URL on every input change.
handle change is keep track of input changes and adding to the server only when hitting the "add" button or enter.

2019-10-24 18:02 UTC, zolga commented on src/components/Admin/Admin.js
> +  const handleChange = event => {
Done, thanks

2019-10-24 18:02 UTC, zolga commented on src/components/Admin/Admin.js
> +    if (event.key === 'Enter') {
Done, thanks.

2019-10-24 18:02 UTC, zolga commented on src/components/Admin/Admin.js
> +      setLinksList(list.reverse());
I want the top to be the last added

2019-10-24 18:02 UTC, zolga commented on src/components/Admin/admin.css
> +.trimText {
A bit nitpicking, in my opinion, I changed it by your request.

2019-10-24 18:02 UTC, zolga commented on src/components/LiveFrame.js
> +const generateRandomNumber = list => {
Change.

2019-10-24 18:02 UTC, zolga commented on src/components/LiveFrame.js
> +      let links = await getLinks();
Changed.

2019-10-24 18:02 UTC, zolga commented on src/components/LiveFrame.js
> +      fetchFromDb();
Added await

2019-10-24 18:02 UTC, zolga commented on src/components/LiveFrame.js
> +      const random = generateRandomNumber(linksList);
removed the try, thanks

2019-10-24 18:02 UTC, zolga commented on src/components/LiveFrame.js
> +      console.error('error HandleClick');
remove, from above

2019-10-24 18:02 UTC, zolga commented on src/components/LiveFrame.js
> +      setLinksList([...links]);
Remove destructuring

2019-10-24 18:02 UTC, zolga commented on backend/backend.js
> +  return update('links', (list = []) => list.filter(link => link.id !== id));
You absolutely right, I didn't think about this case, I will keep it like that for now, it's a simple app, I don't think it's a big deal - I can open an issue for it. WDYT?

2019-10-24 18:02 UTC, zolga commented on backend/backend.js
> +export async function addNewUrl(link = {}) {
It's array because I'm doing `reverse` to the URLs list so the last that was entered will be the first in the list, its not a must, but I think when you have long list its spare you from scrolling down to see it.
I'm ok with this data structure, if you still think this should be an object, please provide more details, Thanks!

2019-10-24 19:13 UTC, rylandg commented on .eslintrc.json
> +{
Got it.

2019-10-24 19:13 UTC, rylandg commented on package.json
> +    "eslint-plugin-react": "^7.16.0"
Hmmm, I'm not sure we should be changing it from the standard.

2019-10-24 19:13 UTC, rylandg commented on src/components/Admin/Admin.js
> +        id: generateRandomId(),
Ty!

2019-10-24 19:13 UTC, rylandg commented on src/components/Admin/admin.css
> +.trimText {
It's a nitpick but being consistent makes code easier to read.

2019-10-24 19:24 UTC, rylandg requested changes
Overall much improved (thank you). My biggest remaining issues:

* Keep array for Urls but remove Id altogether
* Use the standard linting setup that is used in other templates

2019-10-24 19:24 UTC, rylandg commented on backend/backend.js
> +const links = 'links';
Thank you for changing this! As a nitpick, I think we should use a special casing for constants like `LINKS` to show they are constant.

2019-10-24 19:24 UTC, rylandg commented on backend/backend.js
> +export async function addNewUrl(link = {}) {
I don't think the Id's actually provide anything here. Do you intend to allow duplicate Urls? If not, just store the urls in the array.

2019-10-24 19:24 UTC, rylandg commented on src/components/Admin/Admin.js
> +      setLinksList(list.reverse());
Please read my comment above. TL;DR; keep the array, remove Ids.

2019-10-25 03:24 UTC, zolga commented
@rylandg Please take another look. thanks

2019-10-25 17:35 UTC, rylandg approved these changes
LGTM! Thanks

2019-10-25 19:26 UTC, merged